Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
        config.vm.synced_folder "~/Projects/devops_course/VAGRANT-VMS/myvms/scripts", "/scripts"
    end

    config.vm.network "private_network", ip: "192.168.56.17"
    config.vm.network "public_network", bridge: "Realtek RTL8852BE WiFi 6 802.11ax PCIe Adapter" # No static IP
end